export const RUNTIME_CONTRACT_REASONS = {
  INVALID_SELECTOR_SPEC: 'invalidSelectorSpec',
} as const;

export type RuntimeContractReason =
  (typeof RUNTIME_CONTRACT_REASONS)[keyof typeof RUNTIME_CONTRACT_REASONS];

export const PIPELINE_RUNTIME_REASONS = {
  APPLICABILITY_EVALUATION_FAILED: 'applicabilityEvaluationFailed',
  PREDICATE_EVALUATION_FAILED: 'pipelinePredicateEvaluationFailed',
} as const;

export type PipelineRuntimeReason =
  (typeof PIPELINE_RUNTIME_REASONS)[keyof typeof PIPELINE_RUNTIME_REASONS];

export const EFFECT_RUNTIME_REASONS = {
  EFFECT_BUDGET_CONFIG_INVALID: 'effectBudgetConfigInvalid',
  SUBSET_RUNTIME_VALIDATION_FAILED: 'subsetRuntimeValidationFailed',
  CHOICE_RUNTIME_VALIDATION_FAILED: 'choiceRuntimeValidationFailed',
  CONTROL_FLOW_RUNTIME_VALIDATION_FAILED: 'controlFlowRuntimeValidationFailed',
  RESOURCE_RUNTIME_VALIDATION_FAILED: 'resourceRuntimeValidationFailed',
  CONCEAL_RUNTIME_VALIDATION_FAILED: 'concealRuntimeValidationFailed',
  REVEAL_RUNTIME_VALIDATION_FAILED: 'revealRuntimeValidationFailed',
  TOKEN_RUNTIME_VALIDATION_FAILED: 'tokenRuntimeValidationFailed',
  TURN_FLOW_RUNTIME_VALIDATION_FAILED: 'turnFlowRuntimeValidationFailed',
  VARIABLE_RUNTIME_VALIDATION_FAILED: 'variableRuntimeValidationFailed',
} as const;

export type EffectRuntimeReason =
  (typeof EFFECT_RUNTIME_REASONS)[keyof typeof EFFECT_RUNTIME_REASONS];

export const ILLEGAL_MOVE_REASONS = {
  MOVE_NOT_LEGAL_IN_CURRENT_STATE: 'moveNotLegalInCurrentState',
  MOVE_HAS_INCOMPLETE_PARAMS: 'moveHasIncompleteParams',
  MOVE_PARAMS_INVALID: 'moveParamsInvalid',
  MOVE_PARAMS_NOT_LEGAL_FOR_ACTION: 'moveParamsNotLegalForAction',
  UNKNOWN_ACTION_ID: 'unknownActionId',
  SPECIAL_ACTIVITY_ACCOMPANYING_OP_DISALLOWED: 'specialActivityAccompanyingOpDisallowed',
  SPECIAL_ACTIVITY_COMPOUND_PARAM_CONSTRAINT_FAILED: 'specialActivityCompoundParamConstraintFailed',
  TURN_FLOW_ACTION_CLASS_MISMATCH: 'turnFlowActionClassMismatch',
  FREE_OPERATION_NOT_GRANTED: 'freeOperationNotGranted',
  ACTION_ACTOR_NOT_APPLICABLE: 'actionActorNotApplicable',
  ACTION_EXECUTOR_NOT_APPLICABLE: 'actionExecutorNotApplicable',
  ACTION_NOT_LEGAL_IN_CURRENT_STATE: 'actionNotLegalInCurrentState',
  ACTION_PIPELINE_LEGALITY_PREDICATE_FAILED: 'actionPipelineLegalityPredicateFailed',
  ACTION_PIPELINE_COST_VALIDATION_FAILED: 'actionPipelineCostValidationFailed',
  SIMULTANEOUS_SUBMISSION_COMPOUND_UNSUPPORTED: 'simultaneousSubmissionCompoundUnsupported',
  SIMULTANEOUS_RUNTIME_STATE_REQUIRED: 'simultaneousRuntimeStateRequired',
} as const;

export type IllegalMoveReason =
  (typeof ILLEGAL_MOVE_REASONS)[keyof typeof ILLEGAL_MOVE_REASONS];

export const ILLEGAL_MOVE_REASON_MESSAGES: Readonly<Record<IllegalMoveReason, string>> = {
  [ILLEGAL_MOVE_REASONS.MOVE_NOT_LEGAL_IN_CURRENT_STATE]: 'move is not legal in current state',
  [ILLEGAL_MOVE_REASONS.MOVE_HAS_INCOMPLETE_PARAMS]: 'move has incomplete params',
  [ILLEGAL_MOVE_REASONS.MOVE_PARAMS_INVALID]: 'move params are invalid',
  [ILLEGAL_MOVE_REASONS.MOVE_PARAMS_NOT_LEGAL_FOR_ACTION]: 'params are not legal for this action in current state',
  [ILLEGAL_MOVE_REASONS.UNKNOWN_ACTION_ID]: 'unknown action id',
  [ILLEGAL_MOVE_REASONS.SPECIAL_ACTIVITY_ACCOMPANYING_OP_DISALLOWED]: 'special activity cannot accompany this operation',
  [ILLEGAL_MOVE_REASONS.SPECIAL_ACTIVITY_COMPOUND_PARAM_CONSTRAINT_FAILED]:
    'special activity violates compound param constraints',
  [ILLEGAL_MOVE_REASONS.TURN_FLOW_ACTION_CLASS_MISMATCH]:
    'submitted actionClass conflicts with turn-flow mapping for the action',
  [ILLEGAL_MOVE_REASONS.FREE_OPERATION_NOT_GRANTED]: 'free operation is not granted in current state',
  [ILLEGAL_MOVE_REASONS.ACTION_ACTOR_NOT_APPLICABLE]: 'action actor is not applicable in current state',
  [ILLEGAL_MOVE_REASONS.ACTION_EXECUTOR_NOT_APPLICABLE]: 'action executor is not applicable in current state',
  [ILLEGAL_MOVE_REASONS.ACTION_NOT_LEGAL_IN_CURRENT_STATE]: 'action is not legal in current state',
  [ILLEGAL_MOVE_REASONS.ACTION_PIPELINE_LEGALITY_PREDICATE_FAILED]: 'action pipeline legality predicate failed',
  [ILLEGAL_MOVE_REASONS.ACTION_PIPELINE_COST_VALIDATION_FAILED]: 'action pipeline cost validation failed',
  [ILLEGAL_MOVE_REASONS.SIMULTANEOUS_SUBMISSION_COMPOUND_UNSUPPORTED]:
    'simultaneous submission does not support compound moves',
  [ILLEGAL_MOVE_REASONS.SIMULTANEOUS_RUNTIME_STATE_REQUIRED]:
    'simultaneous strategy requires simultaneous runtime state',
};

export const KERNEL_RUNTIME_REASONS = [
  ILLEGAL_MOVE_REASONS.MOVE_NOT_LEGAL_IN_CURRENT_STATE,
  ILLEGAL_MOVE_REASONS.MOVE_HAS_INCOMPLETE_PARAMS,
  ILLEGAL_MOVE_REASONS.MOVE_PARAMS_INVALID,
  ILLEGAL_MOVE_REASONS.MOVE_PARAMS_NOT_LEGAL_FOR_ACTION,
  ILLEGAL_MOVE_REASONS.UNKNOWN_ACTION_ID,
  ILLEGAL_MOVE_REASONS.SPECIAL_ACTIVITY_ACCOMPANYING_OP_DISALLOWED,
  ILLEGAL_MOVE_REASONS.SPECIAL_ACTIVITY_COMPOUND_PARAM_CONSTRAINT_FAILED,
  ILLEGAL_MOVE_REASONS.TURN_FLOW_ACTION_CLASS_MISMATCH,
  ILLEGAL_MOVE_REASONS.FREE_OPERATION_NOT_GRANTED,
  ILLEGAL_MOVE_REASONS.ACTION_ACTOR_NOT_APPLICABLE,
  ILLEGAL_MOVE_REASONS.ACTION_EXECUTOR_NOT_APPLICABLE,
  ILLEGAL_MOVE_REASONS.ACTION_NOT_LEGAL_IN_CURRENT_STATE,
  ILLEGAL_MOVE_REASONS.ACTION_PIPELINE_LEGALITY_PREDICATE_FAILED,
  ILLEGAL_MOVE_REASONS.ACTION_PIPELINE_COST_VALIDATION_FAILED,
  ILLEGAL_MOVE_REASONS.SIMULTANEOUS_SUBMISSION_COMPOUND_UNSUPPORTED,
  ILLEGAL_MOVE_REASONS.SIMULTANEOUS_RUNTIME_STATE_REQUIRED,
  RUNTIME_CONTRACT_REASONS.INVALID_SELECTOR_SPEC,
  PIPELINE_RUNTIME_REASONS.APPLICABILITY_EVALUATION_FAILED,
  PIPELINE_RUNTIME_REASONS.PREDICATE_EVALUATION_FAILED,
  EFFECT_RUNTIME_REASONS.EFFECT_BUDGET_CONFIG_INVALID,
  EFFECT_RUNTIME_REASONS.SUBSET_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.CHOICE_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.CONTROL_FLOW_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.RESOURCE_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.CONCEAL_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.REVEAL_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.TOKEN_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.TURN_FLOW_RUNTIME_VALIDATION_FAILED,
  EFFECT_RUNTIME_REASONS.VARIABLE_RUNTIME_VALIDATION_FAILED,
] as const;

export type KernelRuntimeReason = (typeof KERNEL_RUNTIME_REASONS)[number];
