import type { Diagnostic } from '../kernel/diagnostics.js';

const COMPILER_DIAGNOSTIC_CODES_HELPERS = Object.freeze({
  CNL_COMPILER_ACTION_CAPABILITY_DUPLICATE: 'CNL_COMPILER_ACTION_CAPABILITY_DUPLICATE',
  CNL_COMPILER_ACTION_PHASE_DUPLICATE: 'CNL_COMPILER_ACTION_PHASE_DUPLICATE',
  CNL_COMPILER_BINDING_SHADOWED: 'CNL_COMPILER_BINDING_SHADOWED',
  CNL_COMPILER_MISSING_CAPABILITY: 'CNL_COMPILER_MISSING_CAPABILITY',
  CNL_COMPILER_TURN_STRUCTURE_LEGACY_FIELD_UNSUPPORTED: 'CNL_COMPILER_TURN_STRUCTURE_LEGACY_FIELD_UNSUPPORTED',
  CNL_COMPILER_ZONE_VAR_TYPE_INVALID: 'CNL_COMPILER_ZONE_VAR_TYPE_INVALID',
} as const);

const COMPILER_DIAGNOSTIC_CODES_ACTION_PIPELINE = Object.freeze({
  CNL_COMPILER_ACTION_PIPELINE_ACTION_MAPPING_AMBIGUOUS: 'CNL_COMPILER_ACTION_PIPELINE_ACTION_MAPPING_AMBIGUOUS',
  CNL_COMPILER_ACTION_PIPELINE_DUPLICATE_ID: 'CNL_COMPILER_ACTION_PIPELINE_DUPLICATE_ID',
  CNL_COMPILER_ACTION_PIPELINE_INVALID: 'CNL_COMPILER_ACTION_PIPELINE_INVALID',
  CNL_COMPILER_ACTION_PIPELINE_LINKED_WINDOWS_INVALID: 'CNL_COMPILER_ACTION_PIPELINE_LINKED_WINDOWS_INVALID',
  CNL_COMPILER_ACTION_PIPELINE_REQUIRED_FIELD_MISSING: 'CNL_COMPILER_ACTION_PIPELINE_REQUIRED_FIELD_MISSING',
  CNL_COMPILER_ACTION_PIPELINE_UNKNOWN_ACTION: 'CNL_COMPILER_ACTION_PIPELINE_UNKNOWN_ACTION',
} as const);

const COMPILER_DIAGNOSTIC_CODES_EVENT_CARDS = Object.freeze({
  CNL_COMPILER_EVENT_CARD_BRANCH_ID_DUPLICATE: 'CNL_COMPILER_EVENT_CARD_BRANCH_ID_DUPLICATE',
  CNL_COMPILER_EVENT_CARD_BRANCH_ORDER_AMBIGUOUS: 'CNL_COMPILER_EVENT_CARD_BRANCH_ORDER_AMBIGUOUS',
  CNL_COMPILER_EVENT_CARD_ID_DUPLICATE: 'CNL_COMPILER_EVENT_CARD_ID_DUPLICATE',
  CNL_COMPILER_EVENT_CARD_ORDER_AMBIGUOUS: 'CNL_COMPILER_EVENT_CARD_ORDER_AMBIGUOUS',
  CNL_COMPILER_EVENT_DECK_ID_DUPLICATE: 'CNL_COMPILER_EVENT_DECK_ID_DUPLICATE',
} as const);

const COMPILER_DIAGNOSTIC_CODES_ACTION_SELECTOR = Object.freeze({
  CNL_COMPILER_ACTION_ACTOR_BINDING_INVALID: 'CNL_COMPILER_ACTION_ACTOR_BINDING_INVALID',
  CNL_COMPILER_ACTION_ACTOR_BINDING_MISSING: 'CNL_COMPILER_ACTION_ACTOR_BINDING_MISSING',
  CNL_COMPILER_ACTION_EXECUTOR_BINDING_INVALID: 'CNL_COMPILER_ACTION_EXECUTOR_BINDING_INVALID',
  CNL_COMPILER_ACTION_EXECUTOR_BINDING_MISSING: 'CNL_COMPILER_ACTION_EXECUTOR_BINDING_MISSING',
} as const);

const COMPILER_DIAGNOSTIC_CODES_CONDITIONS_SELECTORS_BINDINGS = Object.freeze({
  CNL_COMPILER_BINDING_SHADOWED: 'CNL_COMPILER_BINDING_SHADOWED',
  CNL_COMPILER_BINDING_UNBOUND: 'CNL_COMPILER_BINDING_UNBOUND',
  CNL_COMPILER_CONDITION_TYPE_MISMATCH: 'CNL_COMPILER_CONDITION_TYPE_MISMATCH',
  CNL_COMPILER_NEXT_IN_ORDER_BIND_INVALID: 'CNL_COMPILER_NEXT_IN_ORDER_BIND_INVALID',
  CNL_COMPILER_PLAYER_SELECTOR_INVALID: 'CNL_COMPILER_PLAYER_SELECTOR_INVALID',
  CNL_COMPILER_TOKEN_FILTER_PROP_UNKNOWN: 'CNL_COMPILER_TOKEN_FILTER_PROP_UNKNOWN',
  CNL_COMPILER_TOKEN_FILTER_VALUE_NON_CANONICAL: 'CNL_COMPILER_TOKEN_FILTER_VALUE_NON_CANONICAL',
  CNL_COMPILER_UNKNOWN_NAMED_SET: 'CNL_COMPILER_UNKNOWN_NAMED_SET',
  CNL_COMPILER_ZONE_SELECTOR_AMBIGUOUS: 'CNL_COMPILER_ZONE_SELECTOR_AMBIGUOUS',
  CNL_COMPILER_ZONE_SELECTOR_INVALID: 'CNL_COMPILER_ZONE_SELECTOR_INVALID',
  CNL_COMPILER_ZONE_SELECTOR_UNKNOWN_BASE: 'CNL_COMPILER_ZONE_SELECTOR_UNKNOWN_BASE',
} as const);

const COMPILER_DIAGNOSTIC_CODES_EFFECTS_AND_MACROS = Object.freeze({
  CNL_COMPILER_DISTRIBUTE_TOKENS_DESTINATION_DOMAIN_INVALID: 'CNL_COMPILER_DISTRIBUTE_TOKENS_DESTINATION_DOMAIN_INVALID',
  CNL_COMPILER_DISTRIBUTE_TOKENS_TOKEN_DOMAIN_INVALID: 'CNL_COMPILER_DISTRIBUTE_TOKENS_TOKEN_DOMAIN_INVALID',
  CNL_COMPILER_FREE_OPERATION_SEQUENCE_VIABILITY_RISK: 'CNL_COMPILER_FREE_OPERATION_SEQUENCE_VIABILITY_RISK',
  CNL_COMPILER_LIMIT_EXCEEDED: 'CNL_COMPILER_LIMIT_EXCEEDED',
  CNL_COMPILER_MACRO_ORIGIN_INVALID: 'CNL_COMPILER_MACRO_ORIGIN_INVALID',
  CNL_COMPILER_MACRO_ORIGIN_UNTRUSTED: 'CNL_COMPILER_MACRO_ORIGIN_UNTRUSTED',
  CNL_COMPILER_RESERVED_BINDING_NAMESPACE_FORBIDDEN: 'CNL_COMPILER_RESERVED_BINDING_NAMESPACE_FORBIDDEN',
  CNL_COMPILER_RESERVED_COMPILER_METADATA_FORBIDDEN: 'CNL_COMPILER_RESERVED_COMPILER_METADATA_FORBIDDEN',
} as const);

const COMPILER_DIAGNOSTIC_CODES_TURN_FLOW = Object.freeze({
  CNL_COMPILER_FIXED_ORDER_DUPLICATE: 'CNL_COMPILER_FIXED_ORDER_DUPLICATE',
  CNL_COMPILER_FIXED_ORDER_EMPTY: 'CNL_COMPILER_FIXED_ORDER_EMPTY',
  CNL_COMPILER_FIXED_ORDER_ENTRY_INVALID: 'CNL_COMPILER_FIXED_ORDER_ENTRY_INVALID',
  CNL_COMPILER_SIMULTANEOUS_NOT_IMPLEMENTED: 'CNL_COMPILER_SIMULTANEOUS_NOT_IMPLEMENTED',
  CNL_COMPILER_TURN_FLOW_ACTION_CLASS_MAP_INVALID: 'CNL_COMPILER_TURN_FLOW_ACTION_CLASS_MAP_INVALID',
  CNL_COMPILER_TURN_FLOW_INVALID: 'CNL_COMPILER_TURN_FLOW_INVALID',
  CNL_COMPILER_TURN_FLOW_ORDERING_CANCELLATION_INVALID: 'CNL_COMPILER_TURN_FLOW_ORDERING_CANCELLATION_INVALID',
  CNL_COMPILER_TURN_FLOW_ORDERING_CANCELLATION_SELECTOR_EMPTY: 'CNL_COMPILER_TURN_FLOW_ORDERING_CANCELLATION_SELECTOR_EMPTY',
  CNL_COMPILER_TURN_FLOW_ORDERING_CANCELLATION_SELECTOR_INVALID: 'CNL_COMPILER_TURN_FLOW_ORDERING_CANCELLATION_SELECTOR_INVALID',
  CNL_COMPILER_TURN_FLOW_ORDERING_DUPLICATE_OPTION_ROW: 'CNL_COMPILER_TURN_FLOW_ORDERING_DUPLICATE_OPTION_ROW',
  CNL_COMPILER_TURN_FLOW_ORDERING_DUPLICATE_SEAT: 'CNL_COMPILER_TURN_FLOW_ORDERING_DUPLICATE_SEAT',
  CNL_COMPILER_TURN_FLOW_ORDERING_PIVOTAL_ACTION_ID_INVALID: 'CNL_COMPILER_TURN_FLOW_ORDERING_PIVOTAL_ACTION_ID_INVALID',
  CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_DUPLICATE: 'CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_DUPLICATE',
  CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_INVALID_SEAT: 'CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_INVALID_SEAT',
  CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_REQUIRED: 'CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_REQUIRED',
  CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_UNKNOWN_SEAT: 'CNL_COMPILER_TURN_FLOW_ORDERING_PRECEDENCE_UNKNOWN_SEAT',
  CNL_COMPILER_TURN_FLOW_ORDERING_SEAT_INVALID: 'CNL_COMPILER_TURN_FLOW_ORDERING_SEAT_INVALID',
  CNL_COMPILER_TURN_FLOW_REQUIRED_FIELD_MISSING: 'CNL_COMPILER_TURN_FLOW_REQUIRED_FIELD_MISSING',
  CNL_COMPILER_TURN_ORDER_CARD_DRIVEN_CONFIG_REQUIRED: 'CNL_COMPILER_TURN_ORDER_CARD_DRIVEN_CONFIG_REQUIRED',
  CNL_COMPILER_TURN_ORDER_INVALID: 'CNL_COMPILER_TURN_ORDER_INVALID',
  CNL_COMPILER_TURN_ORDER_UNSUPPORTED_TYPE: 'CNL_COMPILER_TURN_ORDER_UNSUPPORTED_TYPE',
} as const);

const COMPILER_DIAGNOSTIC_CODES_VICTORY = Object.freeze({
  CNL_COMPILER_COUP_PLAN_FINAL_ROUND_OMIT_INVALID: 'CNL_COMPILER_COUP_PLAN_FINAL_ROUND_OMIT_INVALID',
  CNL_COMPILER_COUP_PLAN_FINAL_ROUND_OMIT_UNKNOWN_PHASE: 'CNL_COMPILER_COUP_PLAN_FINAL_ROUND_OMIT_UNKNOWN_PHASE',
  CNL_COMPILER_COUP_PLAN_INVALID: 'CNL_COMPILER_COUP_PLAN_INVALID',
  CNL_COMPILER_COUP_PLAN_MAX_CONSECUTIVE_INVALID: 'CNL_COMPILER_COUP_PLAN_MAX_CONSECUTIVE_INVALID',
  CNL_COMPILER_COUP_PLAN_PHASES_EMPTY: 'CNL_COMPILER_COUP_PLAN_PHASES_EMPTY',
  CNL_COMPILER_COUP_PLAN_PHASE_DUPLICATE: 'CNL_COMPILER_COUP_PLAN_PHASE_DUPLICATE',
  CNL_COMPILER_COUP_PLAN_PHASE_ID_INVALID: 'CNL_COMPILER_COUP_PLAN_PHASE_ID_INVALID',
  CNL_COMPILER_COUP_PLAN_PHASE_INVALID: 'CNL_COMPILER_COUP_PLAN_PHASE_INVALID',
  CNL_COMPILER_COUP_PLAN_PHASE_STEPS_INVALID: 'CNL_COMPILER_COUP_PLAN_PHASE_STEPS_INVALID',
  CNL_COMPILER_COUP_PLAN_REQUIRED_FIELD_MISSING: 'CNL_COMPILER_COUP_PLAN_REQUIRED_FIELD_MISSING',
  CNL_COMPILER_VICTORY_CHECKPOINT_DUPLICATE: 'CNL_COMPILER_VICTORY_CHECKPOINT_DUPLICATE',
  CNL_COMPILER_VICTORY_CHECKPOINT_ID_INVALID: 'CNL_COMPILER_VICTORY_CHECKPOINT_ID_INVALID',
  CNL_COMPILER_VICTORY_CHECKPOINT_INVALID: 'CNL_COMPILER_VICTORY_CHECKPOINT_INVALID',
  CNL_COMPILER_VICTORY_CHECKPOINT_SEAT_INVALID: 'CNL_COMPILER_VICTORY_CHECKPOINT_SEAT_INVALID',
  CNL_COMPILER_VICTORY_CHECKPOINT_TIMING_INVALID: 'CNL_COMPILER_VICTORY_CHECKPOINT_TIMING_INVALID',
  CNL_COMPILER_VICTORY_CHECKPOINT_WHEN_INVALID: 'CNL_COMPILER_VICTORY_CHECKPOINT_WHEN_INVALID',
  CNL_COMPILER_VICTORY_MARGINS_INVALID: 'CNL_COMPILER_VICTORY_MARGINS_INVALID',
  CNL_COMPILER_VICTORY_MARGIN_INVALID: 'CNL_COMPILER_VICTORY_MARGIN_INVALID',
  CNL_COMPILER_VICTORY_MARGIN_SEAT_INVALID: 'CNL_COMPILER_VICTORY_MARGIN_SEAT_INVALID',
  CNL_COMPILER_VICTORY_MARGIN_VALUE_INVALID: 'CNL_COMPILER_VICTORY_MARGIN_VALUE_INVALID',
  CNL_COMPILER_VICTORY_RANKING_INVALID: 'CNL_COMPILER_VICTORY_RANKING_INVALID',
  CNL_COMPILER_VICTORY_RANKING_ORDER_INVALID: 'CNL_COMPILER_VICTORY_RANKING_ORDER_INVALID',
  CNL_COMPILER_VICTORY_RANKING_TIEBREAK_ORDER_INVALID: 'CNL_COMPILER_VICTORY_RANKING_TIEBREAK_ORDER_INVALID',
  CNL_COMPILER_VICTORY_REQUIRED_FIELD_MISSING: 'CNL_COMPILER_VICTORY_REQUIRED_FIELD_MISSING',
} as const);

const COMPILER_DIAGNOSTIC_CODES_ZONES = Object.freeze({
  CNL_COMPILER_ZONE_ADJACENCY_DIRECTION_INVALID: 'CNL_COMPILER_ZONE_ADJACENCY_DIRECTION_INVALID',
  CNL_COMPILER_ZONE_ADJACENCY_INVALID: 'CNL_COMPILER_ZONE_ADJACENCY_INVALID',
  CNL_COMPILER_ZONE_ID_INVALID: 'CNL_COMPILER_ZONE_ID_INVALID',
  CNL_COMPILER_ZONE_KIND_INVALID: 'CNL_COMPILER_ZONE_KIND_INVALID',
  CNL_COMPILER_ZONE_ORDERING_INVALID: 'CNL_COMPILER_ZONE_ORDERING_INVALID',
  CNL_COMPILER_ZONE_OWNER_INVALID: 'CNL_COMPILER_ZONE_OWNER_INVALID',
  CNL_COMPILER_ZONE_SELECTOR_AMBIGUOUS: 'CNL_COMPILER_ZONE_SELECTOR_AMBIGUOUS',
  CNL_COMPILER_ZONE_SELECTOR_INVALID: 'CNL_COMPILER_ZONE_SELECTOR_INVALID',
  CNL_COMPILER_ZONE_SELECTOR_UNKNOWN_BASE: 'CNL_COMPILER_ZONE_SELECTOR_UNKNOWN_BASE',
  CNL_COMPILER_ZONE_VAR_TYPE_INVALID: 'CNL_COMPILER_ZONE_VAR_TYPE_INVALID',
  CNL_COMPILER_ZONE_VISIBILITY_INVALID: 'CNL_COMPILER_ZONE_VISIBILITY_INVALID',
} as const);

const COMPILER_DIAGNOSTIC_CODES_TABLE_REFS = Object.freeze({
  CNL_COMPILER_TABLE_REF_LEGACY_LITERAL: 'CNL_COMPILER_TABLE_REF_LEGACY_LITERAL',
  CNL_COMPILER_TABLE_REF_PATH_UNKNOWN: 'CNL_COMPILER_TABLE_REF_PATH_UNKNOWN',
  CNL_COMPILER_TABLE_REF_SCENARIO_REQUIRED: 'CNL_COMPILER_TABLE_REF_SCENARIO_REQUIRED',
} as const);

const COMPILER_DIAGNOSTIC_CODES_DATA_ASSETS = Object.freeze({
  CNL_COMPILER_DATA_ASSET_AMBIGUOUS: 'CNL_COMPILER_DATA_ASSET_AMBIGUOUS',
  CNL_COMPILER_DATA_ASSET_REF_MISSING: 'CNL_COMPILER_DATA_ASSET_REF_MISSING',
  CNL_COMPILER_DATA_ASSET_SCENARIO_AMBIGUOUS: 'CNL_COMPILER_DATA_ASSET_SCENARIO_AMBIGUOUS',
  CNL_COMPILER_DATA_ASSET_SCENARIO_SELECTOR_MISSING: 'CNL_COMPILER_DATA_ASSET_SCENARIO_SELECTOR_MISSING',
  CNL_COMPILER_RUNTIME_TABLE_CONSTRAINTS_INVALID: 'CNL_COMPILER_RUNTIME_TABLE_CONSTRAINTS_INVALID',
  CNL_COMPILER_RUNTIME_TABLE_CONSTRAINT_INVALID: 'CNL_COMPILER_RUNTIME_TABLE_CONSTRAINT_INVALID',
  CNL_COMPILER_RUNTIME_TABLE_CONTRACTS_INVALID: 'CNL_COMPILER_RUNTIME_TABLE_CONTRACTS_INVALID',
  CNL_COMPILER_RUNTIME_TABLE_CONTRACT_INVALID: 'CNL_COMPILER_RUNTIME_TABLE_CONTRACT_INVALID',
  CNL_COMPILER_RUNTIME_TABLE_CONTRACT_PATH_DUPLICATE: 'CNL_COMPILER_RUNTIME_TABLE_CONTRACT_PATH_DUPLICATE',
  CNL_COMPILER_RUNTIME_TABLE_CONTRACT_PATH_INVALID: 'CNL_COMPILER_RUNTIME_TABLE_CONTRACT_PATH_INVALID',
  CNL_COMPILER_RUNTIME_TABLE_CONTRACT_PATH_UNKNOWN: 'CNL_COMPILER_RUNTIME_TABLE_CONTRACT_PATH_UNKNOWN',
  CNL_COMPILER_RUNTIME_TABLE_UNIQUE_BY_INVALID: 'CNL_COMPILER_RUNTIME_TABLE_UNIQUE_BY_INVALID',
  CNL_COMPILER_SCENARIO_AVAILABLE_POOL_MISSING: 'CNL_COMPILER_SCENARIO_AVAILABLE_POOL_MISSING',
  CNL_COMPILER_SCENARIO_CARD_PLACEMENT_DUPLICATE_CARD_SOURCE: 'CNL_COMPILER_SCENARIO_CARD_PLACEMENT_DUPLICATE_CARD_SOURCE',
  CNL_COMPILER_SCENARIO_CARD_PLACEMENT_UNKNOWN_CARD: 'CNL_COMPILER_SCENARIO_CARD_PLACEMENT_UNKNOWN_CARD',
  CNL_COMPILER_SCENARIO_CARD_PLACEMENT_UNKNOWN_ZONE: 'CNL_COMPILER_SCENARIO_CARD_PLACEMENT_UNKNOWN_ZONE',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_CONFLICTING_FILTERS: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_CONFLICTING_FILTERS',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_DUPLICATE_ID: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_DUPLICATE_ID',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_DUPLICATE_TAG: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_DUPLICATE_TAG',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_EVENT_DECK_AMBIGUOUS: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_EVENT_DECK_AMBIGUOUS',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_EVENT_DECK_MISSING: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_EVENT_DECK_MISSING',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_EVENT_DECK_UNKNOWN: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_EVENT_DECK_UNKNOWN',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_INSUFFICIENT_COUPS: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_INSUFFICIENT_COUPS',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_INSUFFICIENT_EVENTS: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_INSUFFICIENT_EVENTS',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_COVERAGE_INCOMPLETE: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_COVERAGE_INCOMPLETE',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_OVERLAP: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_OVERLAP',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_PILE_DUPLICATE: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_PILE_DUPLICATE',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_PILE_OUT_OF_RANGE: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_PILE_OUT_OF_RANGE',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_SELECTOR_REQUIRED: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_SELECTOR_REQUIRED',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_UNKNOWN_METADATA_KEY: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_PILE_FILTER_UNKNOWN_METADATA_KEY',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_STRATEGY_UNKNOWN: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_STRATEGY_UNKNOWN',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_UNKNOWN_CARD: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_UNKNOWN_CARD',
  CNL_COMPILER_SCENARIO_DECK_COMPOSITION_UNKNOWN_TAG: 'CNL_COMPILER_SCENARIO_DECK_COMPOSITION_UNKNOWN_TAG',
  CNL_COMPILER_SCENARIO_OUT_OF_PLAY_PIECE_INVALID: 'CNL_COMPILER_SCENARIO_OUT_OF_PLAY_PIECE_INVALID',
  CNL_COMPILER_SCENARIO_OUT_OF_PLAY_POOL_MISSING: 'CNL_COMPILER_SCENARIO_OUT_OF_PLAY_POOL_MISSING',
  CNL_COMPILER_SCENARIO_OUT_OF_PLAY_SEAT_MISMATCH: 'CNL_COMPILER_SCENARIO_OUT_OF_PLAY_SEAT_MISMATCH',
  CNL_COMPILER_SCENARIO_PIECE_CONSERVATION_VIOLATED: 'CNL_COMPILER_SCENARIO_PIECE_CONSERVATION_VIOLATED',
  CNL_COMPILER_SCENARIO_PLACEMENT_PIECE_INVALID: 'CNL_COMPILER_SCENARIO_PLACEMENT_PIECE_INVALID',
  CNL_COMPILER_SCENARIO_PLACEMENT_SEAT_MISMATCH: 'CNL_COMPILER_SCENARIO_PLACEMENT_SEAT_MISMATCH',
  CNL_COMPILER_SCENARIO_SEAT_POOLS_REQUIRED: 'CNL_COMPILER_SCENARIO_SEAT_POOLS_REQUIRED',
} as const);

const COMPILER_DIAGNOSTIC_CODES_PIECE_GENERATION = Object.freeze({
  CNL_COMPILER_PIECE_GEN_BLOCK_INVALID: 'CNL_COMPILER_PIECE_GEN_BLOCK_INVALID',
  CNL_COMPILER_PIECE_GEN_DERIVED_PROP_FROM_UNKNOWN: 'CNL_COMPILER_PIECE_GEN_DERIVED_PROP_FROM_UNKNOWN',
  CNL_COMPILER_PIECE_GEN_DIMENSIONS_EMPTY: 'CNL_COMPILER_PIECE_GEN_DIMENSIONS_EMPTY',
  CNL_COMPILER_PIECE_GEN_DIMENSION_VALUES_EMPTY: 'CNL_COMPILER_PIECE_GEN_DIMENSION_VALUES_EMPTY',
  CNL_COMPILER_PIECE_GEN_DUPLICATE_DIMENSION_NAME: 'CNL_COMPILER_PIECE_GEN_DUPLICATE_DIMENSION_NAME',
  CNL_COMPILER_PIECE_GEN_DUPLICATE_ID: 'CNL_COMPILER_PIECE_GEN_DUPLICATE_ID',
  CNL_COMPILER_PIECE_GEN_ID_PATTERN_NO_PLACEHOLDER: 'CNL_COMPILER_PIECE_GEN_ID_PATTERN_NO_PLACEHOLDER',
  CNL_COMPILER_PIECE_GEN_ID_PATTERN_UNRESOLVED_PLACEHOLDER: 'CNL_COMPILER_PIECE_GEN_ID_PATTERN_UNRESOLVED_PLACEHOLDER',
} as const);

const COMPILER_DIAGNOSTIC_CODES_BATCH_MARKERS = Object.freeze({
  CNL_COMPILER_BATCH_MARKER_DEFAULT_STATE_INVALID: 'CNL_COMPILER_BATCH_MARKER_DEFAULT_STATE_INVALID',
  CNL_COMPILER_BATCH_MARKER_DUPLICATE_ID: 'CNL_COMPILER_BATCH_MARKER_DUPLICATE_ID',
  CNL_COMPILER_BATCH_MARKER_IDS_EMPTY: 'CNL_COMPILER_BATCH_MARKER_IDS_EMPTY',
} as const);

const COMPILER_DIAGNOSTIC_CODES_COMPILER_CORE = Object.freeze({
  CNL_COMPILER_EVENT_ACTION_CAPABILITY_AMBIGUOUS: 'CNL_COMPILER_EVENT_ACTION_CAPABILITY_AMBIGUOUS',
  CNL_COMPILER_REQUIRED_SECTION_MISSING: 'CNL_COMPILER_REQUIRED_SECTION_MISSING',
  CNL_COMPILER_SEAT_CATALOG_REQUIRED: 'CNL_COMPILER_SEAT_CATALOG_REQUIRED',
} as const);

export const CNL_COMPILER_DIAGNOSTIC_CODES = Object.freeze({
  ...COMPILER_DIAGNOSTIC_CODES_HELPERS,
  ...COMPILER_DIAGNOSTIC_CODES_ACTION_PIPELINE,
  ...COMPILER_DIAGNOSTIC_CODES_EVENT_CARDS,
  ...COMPILER_DIAGNOSTIC_CODES_ACTION_SELECTOR,
  ...COMPILER_DIAGNOSTIC_CODES_CONDITIONS_SELECTORS_BINDINGS,
  ...COMPILER_DIAGNOSTIC_CODES_EFFECTS_AND_MACROS,
  ...COMPILER_DIAGNOSTIC_CODES_TURN_FLOW,
  ...COMPILER_DIAGNOSTIC_CODES_VICTORY,
  ...COMPILER_DIAGNOSTIC_CODES_ZONES,
  ...COMPILER_DIAGNOSTIC_CODES_TABLE_REFS,
  ...COMPILER_DIAGNOSTIC_CODES_DATA_ASSETS,
  ...COMPILER_DIAGNOSTIC_CODES_PIECE_GENERATION,
  ...COMPILER_DIAGNOSTIC_CODES_BATCH_MARKERS,
  ...COMPILER_DIAGNOSTIC_CODES_COMPILER_CORE,
} as const);

export type CnlCompilerDiagnosticCode =
  (typeof CNL_COMPILER_DIAGNOSTIC_CODES)[keyof typeof CNL_COMPILER_DIAGNOSTIC_CODES];

interface BuildCompilerMissingCapabilityDiagnosticInput {
  readonly path: string;
  readonly label: string;
  readonly actual: unknown;
  readonly alternatives?: readonly string[];
}

export function buildCompilerBindingShadowWarningDiagnostic(name: string, path: string): Diagnostic {
  return {
    code: CNL_COMPILER_DIAGNOSTIC_CODES.CNL_COMPILER_BINDING_SHADOWED,
    path,
    severity: 'warning',
    message: `Binding "${name}" shadows an outer binding.`,
    suggestion: 'Rename the inner binding to avoid accidental capture.',
  };
}

export function buildCompilerMissingCapabilityDiagnostic({
  path,
  label,
  actual,
  alternatives = [],
}: BuildCompilerMissingCapabilityDiagnosticInput): Diagnostic {
  return {
    code: CNL_COMPILER_DIAGNOSTIC_CODES.CNL_COMPILER_MISSING_CAPABILITY,
    path,
    severity: 'error',
    message: `Cannot lower ${label}: ${formatValue(actual)}.`,
    suggestion: alternatives.length > 0 ? 'Use one of the supported forms.' : 'Use a supported compiler shape.',
    ...(alternatives.length === 0 ? {} : { alternatives: [...alternatives] }),
  };
}

function formatValue(value: unknown): string {
  if (typeof value === 'string') {
    return `"${value}"`;
  }
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}
