const CNL_XREF_DIAGNOSTIC_CODE_PREFIX = 'CNL_XREF_' as const;

export const CNL_XREF_DIAGNOSTIC_CODES = Object.freeze({
  CNL_XREF_ACTION_EXECUTOR_PIPELINE_UNSUPPORTED: 'CNL_XREF_ACTION_EXECUTOR_PIPELINE_UNSUPPORTED',
  CNL_XREF_ACTION_PHASE_MISSING: 'CNL_XREF_ACTION_PHASE_MISSING',
  CNL_XREF_PROFILE_ACTION_MISSING: 'CNL_XREF_PROFILE_ACTION_MISSING',
  CNL_XREF_PROFILE_WINDOW_MISSING: 'CNL_XREF_PROFILE_WINDOW_MISSING',
  CNL_XREF_TURN_FLOW_ACTION_CLASS_ACTION_MISSING: 'CNL_XREF_TURN_FLOW_ACTION_CLASS_ACTION_MISSING',
  CNL_XREF_TURN_FLOW_FREE_OPERATION_ACTION_MISSING: 'CNL_XREF_TURN_FLOW_FREE_OPERATION_ACTION_MISSING',
  CNL_XREF_TURN_FLOW_MONSOON_RESTRICTION_ACTION_MISSING: 'CNL_XREF_TURN_FLOW_MONSOON_RESTRICTION_ACTION_MISSING',
  CNL_XREF_TURN_FLOW_MONSOON_MAX_PARAM_MISSING: 'CNL_XREF_TURN_FLOW_MONSOON_MAX_PARAM_MISSING',
  CNL_XREF_TURN_FLOW_MONSOON_MAX_PARAMS_TOTAL_PARAM_MISSING: 'CNL_XREF_TURN_FLOW_MONSOON_MAX_PARAMS_TOTAL_PARAM_MISSING',
  CNL_XREF_TURN_FLOW_MONSOON_MAX_PARAMS_TOTAL_PARAM_DUPLICATE: 'CNL_XREF_TURN_FLOW_MONSOON_MAX_PARAMS_TOTAL_PARAM_DUPLICATE',
  CNL_XREF_TURN_FLOW_PIVOTAL_CANCELLATION_ACTION_MISSING: 'CNL_XREF_TURN_FLOW_PIVOTAL_CANCELLATION_ACTION_MISSING',
  CNL_XREF_TURN_FLOW_ACTION_CLASS_REQUIRED_MISSING: 'CNL_XREF_TURN_FLOW_ACTION_CLASS_REQUIRED_MISSING',
  CNL_XREF_TURN_FLOW_ACTION_CLASS_REQUIRED_MISMATCH: 'CNL_XREF_TURN_FLOW_ACTION_CLASS_REQUIRED_MISMATCH',
  CNL_XREF_TRIGGER_PHASE_MISSING: 'CNL_XREF_TRIGGER_PHASE_MISSING',
  CNL_XREF_TRIGGER_ACTION_MISSING: 'CNL_XREF_TRIGGER_ACTION_MISSING',
  CNL_XREF_TRIGGER_VAR_MISSING: 'CNL_XREF_TRIGGER_VAR_MISSING',
  CNL_XREF_VICTORY_SEAT_MISSING: 'CNL_XREF_VICTORY_SEAT_MISSING',
  CNL_XREF_MARGIN_SEAT_MISSING: 'CNL_XREF_MARGIN_SEAT_MISSING',
  CNL_XREF_SETUP_ZONE_MISSING: 'CNL_XREF_SETUP_ZONE_MISSING',
  CNL_XREF_SETUP_TOKEN_TYPE_MISSING: 'CNL_XREF_SETUP_TOKEN_TYPE_MISSING',
  CNL_XREF_EFFECT_ZONE_MISSING: 'CNL_XREF_EFFECT_ZONE_MISSING',
  CNL_XREF_EVENT_DECK_ZONE_MISSING: 'CNL_XREF_EVENT_DECK_ZONE_MISSING',
  CNL_XREF_PIVOTAL_PLAY_CONDITION_MISSING: 'CNL_XREF_PIVOTAL_PLAY_CONDITION_MISSING',
  CNL_XREF_LIFECYCLE_ZONE_MISSING: 'CNL_XREF_LIFECYCLE_ZONE_MISSING',
  CNL_XREF_REWARD_VAR_MISSING: 'CNL_XREF_REWARD_VAR_MISSING',
  CNL_XREF_EVENT_DECK_EFFECT_ZONE_MISSING: 'CNL_XREF_EVENT_DECK_EFFECT_ZONE_MISSING',
  CNL_XREF_EVENT_DECK_TARGETS_EXECUTABILITY_MISSING: 'CNL_XREF_EVENT_DECK_TARGETS_EXECUTABILITY_MISSING',
  CNL_XREF_EVENT_DECK_GRANT_SEAT_MISSING: 'CNL_XREF_EVENT_DECK_GRANT_SEAT_MISSING',
  CNL_XREF_EVENT_DECK_GRANT_EXECUTE_AS_SEAT_MISSING: 'CNL_XREF_EVENT_DECK_GRANT_EXECUTE_AS_SEAT_MISSING',
  CNL_XREF_EVENT_DECK_GRANT_ACTION_MISSING: 'CNL_XREF_EVENT_DECK_GRANT_ACTION_MISSING',
  CNL_XREF_EVENT_DECK_OVERRIDE_SEAT_MISSING: 'CNL_XREF_EVENT_DECK_OVERRIDE_SEAT_MISSING',
  CNL_XREF_EVENT_DECK_OVERRIDE_WINDOW_MISSING: 'CNL_XREF_EVENT_DECK_OVERRIDE_WINDOW_MISSING',
  CNL_XREF_ZONEVAR_MISSING: 'CNL_XREF_ZONEVAR_MISSING',
} as const);

export type CnlXrefDiagnosticCode = (typeof CNL_XREF_DIAGNOSTIC_CODES)[keyof typeof CNL_XREF_DIAGNOSTIC_CODES];

export function isCnlXrefDiagnosticCode(code: string): boolean {
  return code.startsWith(CNL_XREF_DIAGNOSTIC_CODE_PREFIX);
}
