export const SUPPORTED_EFFECT_KINDS = [
  'setVar',
  'setActivePlayer',
  'addVar',
  'transferVar',
  'moveToken',
  'moveAll',
  'moveTokenAdjacent',
  'draw',
  'reveal',
  'conceal',
  'shuffle',
  'createToken',
  'destroyToken',
  'setTokenProp',
  'if',
  'forEach',
  'reduce',
  'removeByPriority',
  'let',
  'bindValue',
  'evaluateSubset',
  'chooseOne',
  'chooseN',
  'rollRandom',
  'setMarker',
  'shiftMarker',
  'setGlobalMarker',
  'flipGlobalMarker',
  'shiftGlobalMarker',
  'grantFreeOperation',
  'gotoPhaseExact',
  'advancePhase',
  'pushInterruptPhase',
  'popInterruptPhase',
] as const;

export type SupportedEffectKind = typeof SUPPORTED_EFFECT_KINDS[number];
