pub const STATUS_BAD_OPERAND: i32 = -12;

pub const OUTCOME_COMPLETED: i32 = 1;
pub const OUTCOME_STOCHASTIC: i32 = 2;
pub const OUTCOME_DEPTH_CAP: i32 = 3;
pub const OUTCOME_FAILED: i32 = 4;

pub const PREVIEW_STATUS_READY: i32 = 1;
pub const PREVIEW_STATUS_STOCHASTIC: i32 = 2;
const PREVIEW_STATUS_HIDDEN: i32 = 3;
const PREVIEW_STATUS_UNRESOLVED: i32 = 4;
pub const PREVIEW_STATUS_FAILED: i32 = 5;
pub const PREVIEW_STATUS_DEPTH_CAP: i32 = 6;
const PREVIEW_STATUS_GATED: i32 = 7;
const PREVIEW_BRANCH_NONE: i32 = 0;
const PREVIEW_BRANCH_GREEDY: i32 = 1;
const PREVIEW_BRANCH_CONTINUED_DEEPENING: i32 = 2;
const DECISION_STACK_FRAME_ACTION_SELECTION: i32 = 1;
const DECISION_STACK_FRAME_CHOOSE_ONE: i32 = 2;
const DECISION_STACK_FRAME_CHOOSE_N_STEP: i32 = 3;
const DECISION_STACK_FRAME_STOCHASTIC_RESOLVE: i32 = 4;
const DECISION_STACK_FRAME_OUTCOME_GRANT_RESOLVE: i32 = 5;
const DECISION_STACK_FRAME_TURN_RETIREMENT: i32 = 6;
const PREVIEW_STATE_SLOT_KIND_GLOBAL: i32 = 1;
const PREVIEW_STATE_SLOT_KIND_FEATURE: i32 = 2;
const PREVIEW_STATE_SLOT_KIND_SURFACE: i32 = 3;
const PREVIEW_STATE_SLOT_KIND_GENERIC: i32 = 4;
const PREVIEW_STATE_SLOT_LIFETIME_SINGLE_ITERATION: i32 = 1;
const PREVIEW_STATE_SLOT_LIFETIME_CROSS_ITERATION: i32 = 2;

pub fn read_preview_status(value: i32) -> Result<i32, i32> {
    match value {
        PREVIEW_STATUS_READY | PREVIEW_STATUS_STOCHASTIC | PREVIEW_STATUS_HIDDEN
        | PREVIEW_STATUS_UNRESOLVED | PREVIEW_STATUS_FAILED | PREVIEW_STATUS_DEPTH_CAP
        | PREVIEW_STATUS_GATED => Ok(value),
        _ => Err(STATUS_BAD_OPERAND),
    }
}

pub fn read_outcome(value: i32) -> Result<i32, i32> {
    match value {
        OUTCOME_COMPLETED | OUTCOME_STOCHASTIC | OUTCOME_DEPTH_CAP | OUTCOME_FAILED => Ok(value),
        _ => Err(STATUS_BAD_OPERAND),
    }
}

pub fn read_preview_branch(value: i32) -> Result<i32, i32> {
    match value {
        PREVIEW_BRANCH_NONE | PREVIEW_BRANCH_GREEDY | PREVIEW_BRANCH_CONTINUED_DEEPENING => Ok(value),
        _ => Err(STATUS_BAD_OPERAND),
    }
}

pub fn read_decision_stack_frame_variant(value: i32) -> Result<i32, i32> {
    match value {
        DECISION_STACK_FRAME_ACTION_SELECTION | DECISION_STACK_FRAME_CHOOSE_ONE
        | DECISION_STACK_FRAME_CHOOSE_N_STEP | DECISION_STACK_FRAME_STOCHASTIC_RESOLVE
        | DECISION_STACK_FRAME_OUTCOME_GRANT_RESOLVE | DECISION_STACK_FRAME_TURN_RETIREMENT => Ok(value),
        _ => Err(STATUS_BAD_OPERAND),
    }
}

pub fn read_preview_state_slot_kind(value: i32) -> Result<i32, i32> {
    match value {
        PREVIEW_STATE_SLOT_KIND_GLOBAL | PREVIEW_STATE_SLOT_KIND_FEATURE
        | PREVIEW_STATE_SLOT_KIND_SURFACE | PREVIEW_STATE_SLOT_KIND_GENERIC => Ok(value),
        _ => Err(STATUS_BAD_OPERAND),
    }
}

pub fn read_preview_state_slot_lifetime(value: i32) -> Result<i32, i32> {
    match value {
        PREVIEW_STATE_SLOT_LIFETIME_SINGLE_ITERATION | PREVIEW_STATE_SLOT_LIFETIME_CROSS_ITERATION => Ok(value),
        _ => Err(STATUS_BAD_OPERAND),
    }
}
